### ISSUE TITLE
tsc errors

### ISSUE THREAD

**Issue by klanglie** [jwerts/jsapi4-angular2#6]
I am using TypeScript 2.0 compiller. When I try to build your app, I am receiving the below errors. How did you manage to get around these? I am specifically interested in the esri-related ones. I am trying to upgrade a project of my own and am encountering build errors. When I try to resolve them by using require syntax and Typings then run the app I get runtime errors.

app/app.component.ts(1,35): error TS2307: Cannot find module '@angular/core'.
app/app.component.ts(4,19): error TS2307: Cannot find module 'esri/geometry/Point'.
app/app.component.ts(5,21): error TS2307: Cannot find module 'esri/Graphic'.
app/app.component.ts(6,32): error TS2307: Cannot find module 'esri/symbols/SimpleMarkerSymbol'.
app/app.component.ts(7,19): error TS2307: Cannot find module 'esri/Color'.
app/app.module.ts(1,31): error TS2307: Cannot find module '@angular/core'.
app/app.module.ts(2,31): error TS2307: Cannot find module '@angular/platform-browser'.
app/app.module.ts(3,32): error TS2307: Cannot find module '@angular/http'.
app/attribute.component.ts(1,35): error TS2307: Cannot find module '@angular/core'.
app/attribute.component.ts(3,24): error TS2307: Cannot find module 'esri/core/Collection'.
app/main.ts(1,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
app/map.component.ts(1,61): error TS2307: Cannot find module '@angular/core'.
app/map.component.ts(4,21): error TS2307: Cannot find module 'esri/views/MapView'.
app/map.component.ts(5,19): error TS2307: Cannot find module 'esri/geometry/Point'.
app/map.component.ts(6,30): error TS2307: Cannot find module 'esri/geometry/SpatialReference'.
app/map.service.ts(1,28): error TS2307: Cannot find module '@angular/core'.
app/map.service.ts(3,17): error TS2307: Cannot find module 'esri/Map'.
app/map.service.ts(4,27): error TS2307: Cannot find module 'esri/layers/GraphicsLayer'.
app/points.model.spec.ts(3,21): error TS2307: Cannot find module 'esri/Graphic'.
app/points.model.spec.ts(4,19): error TS2307: Cannot find module 'esri/geometry/Point'.
app/points.model.spec.ts(6,1): error TS2304: Cannot find name 'describe'.
app/points.model.spec.ts(21,3): error TS2304: Cannot find name 'beforeEach'.
app/points.model.spec.ts(25,3): error TS2304: Cannot find name 'it'.
app/points.model.spec.ts(26,5): error TS2304: Cannot find name 'expect'.
app/points.model.spec.ts(27,5): error TS2304: Cannot find name 'expect'.
app/points.model.spec.ts(30,3): error TS2304: Cannot find name 'describe'.
app/points.model.spec.ts(31,5): error TS2304: Cannot find name 'it'.
app/points.model.spec.ts(34,8): error TS2304: Cannot find name 'expect'.
app/points.model.spec.ts(37,5): error TS2304: Cannot find name 'it'.
app/points.model.spec.ts(39,7): error TS2304: Cannot find name 'expect'.
app/points.model.spec.ts(42,5): error TS2304: Cannot find name 'it'.
app/points.model.spec.ts(46,7): error TS2304: Cannot find name 'expect'.
app/points.model.spec.ts(50,3): error TS2304: Cannot find name 'describe'.
app/points.model.spec.ts(51,5): error TS2304: Cannot find name 'it'.
app/points.model.spec.ts(54,7): error TS2304: Cannot find name 'expect'.
app/points.model.ts(1,28): error TS2307: Cannot find module '@angular/core'.
app/points.model.ts(3,21): error TS2307: Cannot find module 'esri/Graphic'.
app/points.model.ts(4,27): error TS2307: Cannot find module 'esri/layers/GraphicsLayer'.
app/points.model.ts(5,24): error TS2307: Cannot find module 'esri/core/Collection'.

**Comment by jwerts** [comment]
i just re-cloned repo fresh, ran `npm install` and `npm start` without any issues.  Can you tell me more about your setup?  Have you made any modifications to the repo?  How are you compiling?

**Comment by klanglie** [comment]
No modifications. I'm actually having an issue running npm install too. 
' Failed at the jsapi4angular2@1.0.0 preinstall script 'bower install'.'
I made sure bower was installed. I am using Windows 10.  Typescript v2.0.3. Node v6.4.0.
Compiling from the command line and am using VS Code for IDE.

**Comment by jwerts** [comment]
Make sure bower is installed globably:  `npm install -g bower`

You should be able to do `bower install` from the command line if bower is installed correctly.

**Comment by klanglie** [comment]
bower is installed and most packages are resolved, except:
bower dgrid#1.0.0-esri                  ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Esri/dgrid.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.253.113]: errno=No such file or directory

**Comment by jwerts** [comment]
`bower install --force` did not have any issues for me, so I'm not sure why that's not resolving.

The bower components are only necessary for the unit testing.  If you want to get back to your original issue, remove preinstall from the scripts property in package.json (https://github.com/jwerts/jsapi4-angular2/blob/master/package.json#L6) and then try `npm install` again so that it finishes.  I think your original issues is that its not installing the typings because bower fails before it can get there.

**Comment by klanglie** [comment]
Yes! That did it.  I wonder why preinstall is failing? I can now run your sample. Thanks so much.

bower dojo#v1.10.4/esri-3.14.0          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Esri/dojo.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.253.112]: errno=No such file or directory

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=No such file or directory
