### ISSUE TITLE
Esri Maps

### ISSUE THREAD

**Issue by benitazz** [jwerts/jsapi4-angular2#7]
Hi,

I have followed your example and used the same pattern on my project. The current problem that I have is that it seems like I cannot change the layers on the fly, what I mean is that I have added a method on the map service to change the tile layers according to the user selection: 

here is my method to add tile layers:

public addTileMapLayer(layerData) {

```
let tileLayer = new TileLayer({
  url: layerData.url,
  title: layerData.name
});

this.map.layers.removeAll();

this.map.add(tileLayer);
```

  }

the above method does not seem to work outside the map service, however if I call the same method in the map service constructor then all is well.

 I would like to be able to call the method when I consume the service on the other component and be able to change the map layers according to the user selection. Please assist

here is an example of calling the map service method from my layer component and the map does not get rendered with the new layer that I have selected :

 public  onClick(legendLayer) {
        var map = this._mapService.map;
        this._mapService.addTileMapLayer(legendLayer);
    }

**Comment by jwerts** [comment]
Your code looks OK from what I see.  Perhaps check the following:
1. Make sure onClick() is actually being called - add a console.log statement to be sure.
2. Try adding a different layer in your addTileMapLayer that doesn't rely on layerData input - just hardcode in a url that you know works.
3. Try adding and removing some layers in a simple non-angular HTML page (or add/remove a few different layers in the map service constructor).  I've found that JSAPI 4.x has some major bugs when it comes to adding/removing layers, setting visibility, etc on the fly.

Let me know if any of that helps!

**Comment by benitazz** [comment]
I have checked and confirmed that my onClick method is being called, I even went as far as printing the layers before and after applying the new layer and can confirm that the map layers are being changed on the map object but for some other strange reason the new layers are not getting rendered. 

As I have stated earlier its weird because addTileMapLayer only works in the constructor of the map service, the other weird part is that even after I created the map using the map service constructor and try to remove the layers then nothing happens, the same layer that I used on the constructor is still rendered but the map object does not have any layers.

I have also created the method for monitoring which layers are being created or removed 

someOthermethod()
.
.
.
    this.map.allLayers.on("change", this.onMapChanged);
  }

  private onMapChanged(event) {
    debugger;
    console.log(event);

```
if (event.added) {
  event.added.forEach(data => { console.log("Added: title" + data.title) });
}

if (event.removed) {
  event.added.forEach(data => { console.log("Removed: title" + data.title) });
}
```

  }

**Comment by jwerts** [comment]
Which version of jsapi are you using?

**Comment by benitazz** [comment]
```
<link rel="stylesheet" href="https://js.arcgis.com/4.1/esri/css/main.css">
```

**Comment by benitazz** [comment]
```
<script src="https://js.arcgis.com/4.1/"></script>
```

**Comment by jwerts** [comment]
Without running your code myself, all I can say is that it seems like a JSAPI bug to me.  I've run into some similar ones with 4.x (notably GraphicsLayer visibility toggle on/off not rendering) so I wouldn't be surprised.

4.2 is due out in November I think.

**Comment by benitazz** [comment]
thank for all your efforts.

 I think I will go back to version 3.18 , I got everything working there

**Comment by jwerts** [comment]
Can't blame you there.  I have a production app in 4.x that has way more bug workarounds than I'd like.  4.x is still a ways from really being production quality, unfortunately.
